/**
 * How a vessel came to be where the map is drawing it.
 *
 * The map already draws positions. What it could not say, until now, is
 * whether a position was *reported* or *worked out* — and those are
 * different claims about the world. A source saying "this ship was here
 * at 14:02" is evidence. A smooth animation between two such reports is
 * the interface being pleasant to look at, and a dashed line ahead of the
 * bow is arithmetic about a future nobody has observed.
 *
 * Drawn identically, they are indistinguishable, and an officer reading a
 * position off the screen has no way to know which of the three they are
 * looking at. That is the failure this module exists to prevent: the
 * moment interpolation is added for smoothness, every displayed position
 * becomes a claim the data does not support unless the distinction is
 * carried in the model rather than remembered by whoever writes the next
 * component.
 *
 * ## This is not the intelligence confidence axis
 *
 * `ConfidenceTier` in `entity-visual` grades how much Seaphore trusts an
 * *assessment*. This grades how a *coordinate* was arrived at. They are
 * orthogonal: a high-confidence risk assessment can be attached to a
 * vessel whose current screen position is pure interpolation, and a
 * perfectly observed position can carry no assessment at all. Collapsing
 * them into one field would make both meaningless.
 */

/**
 * The five ways a coordinate reaches the screen.
 *
 * Ordered by how much the data supports them, strongest first.
 */
export type PositionKind =
  /** A source reported this coordinate at this time. Evidence. */
  | "OBSERVED"
  /**
   * A point on the line between two observations, generated by the
   * interface so a vessel glides rather than jumps.
   *
   * Nobody saw the ship here. It is a drawing convenience, and it is only
   * defensible while it stays labelled as one.
   */
  | "DISPLAY_INTERPOLATED"
  /**
   * Calculated from observations by a stated method — dead reckoning from
   * a last known course and speed, for instance.
   *
   * Distinct from interpolation because it is not bounded by two
   * observations: it extends past the last one, so its error grows with
   * time rather than staying between two known points.
   */
  | "ESTIMATED"
  /** A future position. Nothing has happened here yet. */
  | "PROJECTED"
  /**
   * Not a position at all — the coordinate of a place a record names.
   *
   * NPA reports that a vessel is at a berth in Lagos. That is a fact
   * about the vessel, and the port has a coordinate, but the two do not
   * combine into a position: nobody observed the ship at the port
   * centroid, and the berth it is actually at has no published geometry.
   *
   * It is last in this list because it is the weakest claim on the map —
   * weaker even than a projection, which is at least derived from an
   * observation of this vessel. This is derived from an observation of
   * nothing but a spreadsheet cell naming a place. Drawn as a place, it
   * is honest; drawn as a fix, it is fabrication.
   */
  | "ADMINISTRATIVE";

/** Every kind, strongest evidence first. */
export const POSITION_KINDS: readonly PositionKind[] = [
  "OBSERVED",
  "DISPLAY_INTERPOLATED",
  "ESTIMATED",
  "PROJECTED",
  "ADMINISTRATIVE",
] as const;

/**
 * What an officer is told about a position of this kind.
 *
 * Short, because these appear beside a coordinate rather than in prose,
 * and plain, because the officer is being told what the system knows —
 * not how it is implemented.
 */
export const POSITION_KIND_LABELS: Readonly<Record<PositionKind, string>> = {
  OBSERVED: "Observed",
  DISPLAY_INTERPOLATED: "Between reports",
  ESTIMATED: "Estimated",
  PROJECTED: "Projected",
  ADMINISTRATIVE: "Place, not position",
};

/**
 * The longer sentence, for a drawer or a tooltip.
 *
 * Each says plainly whether anybody saw the vessel there, because that is
 * the question the label is standing in for.
 */
export const POSITION_KIND_DETAIL: Readonly<Record<PositionKind, string>> = {
  OBSERVED: "A source reported this position.",
  DISPLAY_INTERPOLATED:
    "Drawn between two reported positions so the track is continuous. The vessel was not observed here.",
  ESTIMATED: "Calculated from the last reported position, course and speed. Not observed.",
  PROJECTED: "Where the vessel would be if it holds its present course and speed. Not observed.",
  ADMINISTRATIVE:
    "The coordinate of a place a record names, not a report of where the vessel is. Nobody observed it here.",
};

/**
 * Whether a position is evidence of where a vessel actually was.
 *
 * The single question most callers need, and the one worth making hard to
 * get wrong: anything that records, exports, reports or investigates must
 * filter on this rather than assume the positions it holds are reports.
 */
export function isObserved(kind: PositionKind | undefined): boolean {
  // Absent means observed. Every position predating this field came from
  // a source report — nothing in the codebase generated positions — so
  // the default preserves the meaning those callers already had.
  return kind === undefined || kind === "OBSERVED";
}

/**
 * Whether a position may be presented as a factual location claim.
 *
 * The same test as {@link isObserved}, named for the decision it governs
 * rather than the property it reads. A caller asking "can I say the
 * vessel was here?" should not have to translate that into a question
 * about enum membership.
 */
export function mayClaimAsFact(kind: PositionKind | undefined): boolean {
  return isObserved(kind);
}

/**
 * How a track of this kind should be drawn.
 *
 * Line style rather than colour alone, deliberately. Colour is already
 * carrying risk and freshness on this map, and a fourth meaning layered
 * onto the same channel would be unreadable — and invisible to an officer
 * with a colour vision deficiency. A solid line and a dashed line differ
 * in a way that survives both.
 *
 * The dash arrays are in the units MapLibre's `line-dasharray` uses:
 * multiples of the line width.
 */
export interface PositionKindStroke {
  /** `undefined` means a solid line. */
  readonly dashArray?: readonly [number, number];
  /** Multiplier on the base line opacity. */
  readonly opacity: number;
}

export const POSITION_KIND_STROKES: Readonly<Record<PositionKind, PositionKindStroke>> = {
  // Solid and full strength: this is the thing that actually happened.
  OBSERVED: { opacity: 1 },
  /*
   * Interpolation joins two observations, so the officer is looking at a
   * real segment of track with an unobserved interior. It stays solid so
   * the track reads as continuous, and drops in weight so it is plainly
   * subordinate to the reports at either end.
   */
  DISPLAY_INTERPOLATED: { opacity: 0.55 },
  ESTIMATED: { dashArray: [2, 1.5], opacity: 0.7 },
  // The longest gaps, because it is the weakest claim on the map.
  PROJECTED: { dashArray: [1, 2], opacity: 0.5 },
  /*
   * The faintest and the most broken up. It is the only kind on this
   * list that is not about this vessel's movement at all, and it must
   * never read as a track.
   */
  ADMINISTRATIVE: { dashArray: [1, 3], opacity: 0.4 },
};

/**
 * The strongest kind present in a set.
 *
 * A summary of a mixed track must describe itself by its *weakest* claim,
 * not its strongest — so this exists mainly to be used by
 * {@link weakestPositionKind}'s callers as its counterpart, and is kept
 * separate so neither is reached for by accident.
 */
export function strongestPositionKind(kinds: readonly PositionKind[]): PositionKind | null {
  for (const kind of POSITION_KINDS) if (kinds.includes(kind)) return kind;
  return null;
}

/**
 * The weakest kind present in a set.
 *
 * What a mixed track should be labelled with. A path that is nine-tenths
 * observed and one-tenth projected is not an observed path: the officer
 * needs to know that some of what they are looking at has not happened.
 */
export function weakestPositionKind(kinds: readonly PositionKind[]): PositionKind | null {
  for (let i = POSITION_KINDS.length - 1; i >= 0; i--) {
    const kind = POSITION_KINDS[i]!;
    if (kinds.includes(kind)) return kind;
  }
  return null;
}
