/**
 * The path a vessel actually took, and what that path is worth.
 *
 * The map can now say where a vessel is. This is what lets it say where
 * the vessel has been — and, just as importantly, when it cannot.
 *
 * ## Two states, because there are only two honest ones
 *
 * `RECORDED_TRACK` is points a source reported. `UNAVAILABLE` is
 * everything else. There is deliberately no estimated-route state: a
 * line drawn from a destination LOCODE to a current position would be a
 * great-circle guess wearing the visual language of evidence, and no
 * connected source provides geocoded origins or destinations to build a
 * real one from. That state returns when a source does.
 *
 * ## Capability and data are separate answers
 *
 * A source that keeps no archive is a limit of what Seaphore is
 * connected to. A source that keeps one and holds nothing for this hull
 * is a fact about the vessel. Collapsing them into "no history" would
 * tell an officer the ship sat still when the truth is that nobody was
 * recording, so the unavailable state carries which one it is.
 *
 * ## Nothing is smoothed
 *
 * Reports arrive at intervals; the space between two of them is not
 * something anyone observed. Points are passed through exactly as the
 * source gave them, with their own timestamps and provenance, and the
 * renderer joins them with straight segments that claim nothing more
 * than "these two positions were reported in this order".
 */
import { getVesselSource } from "./vessel-source";
import type { VesselHistory, VesselTrackPoint } from "./vessel-history";
import type { GeoJsonFeature, GeoJsonFeatureCollection, LonLat } from "./types";

/** Why a track cannot be drawn. */
export type TrackUnavailableReason =
  /** The active source keeps no archive at all. */
  | "SOURCE_HAS_NO_HISTORY"
  /** The source keeps an archive and holds nothing for this vessel. */
  | "NO_RECORDS_FOR_VESSEL"
  /** The archive was asked and could not answer. */
  | "LOOKUP_FAILED";

export type VesselTrack =
  | {
      readonly state: "RECORDED_TRACK";
      readonly points: readonly VesselTrackPoint[];
      /** ISO-8601 bounds of what was actually returned. */
      readonly from: string;
      readonly to: string;
      /** Whether the source that produced this is a simulation. */
      readonly simulated: boolean;
    }
  | {
      readonly state: "UNAVAILABLE";
      readonly reason: TrackUnavailableReason;
    };

/**
 * What an officer is told about the track, in one line.
 *
 * Derived from the source's declared type, never from a vessel id, so a
 * provider added later gets correct wording by declaring what it is. The
 * simulation must never be described with the vocabulary of a real feed
 * — "recorded" and "reported" both imply something happened.
 */
export function trackProvenanceLabel(track: VesselTrack): string {
  if (track.state === "UNAVAILABLE") return TRACK_UNAVAILABLE_LABEL[track.reason];
  return track.simulated
    ? "Simulated movement history generated by the connected demonstration source."
    : "Movement history provided by the connected source.";
}

/** Short form, for a field value rather than a sentence. */
export function trackStateLabel(track: VesselTrack): string {
  if (track.state === "UNAVAILABLE") return "Unavailable";
  return track.simulated ? "Simulated track" : "Recorded track";
}

export const TRACK_UNAVAILABLE_LABEL: Readonly<Record<TrackUnavailableReason, string>> = {
  SOURCE_HAS_NO_HISTORY: "Historical movement is not available from the connected source.",
  NO_RECORDS_FOR_VESSEL: "The connected source holds no recorded movement for this vessel.",
  LOOKUP_FAILED: "Movement history could not be read from the connected source.",
};

/**
 * Turn a history result into a track, or an account of its absence.
 *
 * Takes the already-resolved history rather than fetching, so the
 * decision is pure and the caller keeps ownership of when the archive is
 * asked.
 *
 * A single point is not a track. One position is where the vessel was
 * once; drawing it as a path would imply a journey between a point and
 * itself, so it reports as no records rather than rendering nothing and
 * leaving the officer to wonder whether the line failed to draw.
 */
export function resolveVesselTrack(
  history: VesselHistory | null,
  sourceId: string | null | undefined,
): VesselTrack {
  if (!history) return { state: "UNAVAILABLE", reason: "SOURCE_HAS_NO_HISTORY" };
  if (history.status === "unavailable") {
    return { state: "UNAVAILABLE", reason: "NO_RECORDS_FOR_VESSEL" };
  }
  if (history.track.length < 2) {
    return { state: "UNAVAILABLE", reason: "NO_RECORDS_FOR_VESSEL" };
  }

  const descriptor = sourceId ? getVesselSource(sourceId)?.describe() : undefined;
  return {
    state: "RECORDED_TRACK",
    points: history.track,
    from: history.from,
    to: history.to,
    simulated: descriptor?.type === "SIMULATED",
  };
}

/** Properties the renderer reads off the track feature. */
export interface TrackLineProperties {
  readonly simulated: boolean;
  /** Point count, so a sparse track can be drawn as sparsely as it is. */
  readonly pointCount: number;
}

export type TrackLineFeature = GeoJsonFeature<
  { readonly type: "LineString"; readonly coordinates: readonly LonLat[] },
  TrackLineProperties
>;

export type TrackCollection = GeoJsonFeatureCollection<
  { readonly type: "LineString"; readonly coordinates: readonly LonLat[] },
  TrackLineProperties
>;

/** An empty collection — what the renderer draws when there is no track. */
export const EMPTY_TRACK: TrackCollection = { type: "FeatureCollection", features: [] };

/**
 * The track as one line the map engine can draw.
 *
 * A single feature rather than one per segment: the whole path is one
 * claim about one vessel, and a source per point would put thousands of
 * features on the map to say what one line says.
 *
 * Coordinates are the reported positions in order, untouched. Nothing is
 * resampled, smoothed, or padded to make the line look better — the
 * shape of the data is part of what the officer is reading.
 */
export function toTrackCollection(track: VesselTrack): TrackCollection {
  if (track.state !== "RECORDED_TRACK") return EMPTY_TRACK;
  return {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        geometry: {
          type: "LineString",
          coordinates: track.points.map((point) => point.position),
        },
        properties: { simulated: track.simulated, pointCount: track.points.length },
      },
    ],
  };
}
