/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VesselRouteImport } from './routes/vessel'
import { Route as ShareRouteImport } from './routes/share'
import { Route as RevenueLeakageRouteImport } from './routes/revenue-leakage'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as PortsRouteImport } from './routes/ports'
import { Route as OwnershipRouteImport } from './routes/ownership'
import { Route as OperationalKnowledgeRouteImport } from './routes/operational-knowledge'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as NationalRiskRouteImport } from './routes/national-risk'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ManifestRouteImport } from './routes/manifest'
import { Route as KnowledgeGraphRouteImport } from './routes/knowledge-graph'
import { Route as InvestigationsWorkflowRouteImport } from './routes/investigations-workflow'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as InvestigateRouteImport } from './routes/investigate'
import { Route as IntelligenceEvidenceRouteImport } from './routes/intelligence-evidence'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as DetectRouteImport } from './routes/detect'
import { Route as DecideRouteImport } from './routes/decide'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as CargoWorkspaceRouteImport } from './routes/cargo-workspace'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as BriefingCentreRouteImport } from './routes/briefing-centre'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as ShareIndexRouteImport } from './routes/share.index'
import { Route as InvestigateIndexRouteImport } from './routes/investigate.index'
import { Route as DecideIndexRouteImport } from './routes/decide.index'
import { Route as CargoWorkspaceIndexRouteImport } from './routes/cargo-workspace.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WorkspaceIdRouteImport } from './routes/workspace.$id'
import { Route as ShareQueueRouteImport } from './routes/share.queue'
import { Route as ShareIdRouteImport } from './routes/share.$id'
import { Route as InvestigateOpenRouteImport } from './routes/investigate.open'
import { Route as InvestigateIdRouteImport } from './routes/investigate.$id'
import { Route as EntityIdRouteImport } from './routes/entity.$id'
import { Route as DecideQueueRouteImport } from './routes/decide.queue'
import { Route as DecideIdRouteImport } from './routes/decide.$id'
import { Route as CargoWorkspaceCentreRouteImport } from './routes/cargo-workspace.$centre'
import { Route as AdminProviderHealthRouteImport } from './routes/admin.provider-health'
import { Route as AdminProjectionContractRouteImport } from './routes/admin.projection-contract'
import { Route as AdminOsintRouteImport } from './routes/admin.osint'
import { Route as AdminConnectorsRouteImport } from './routes/admin.connectors'
import { Route as ApiSessionIdRouteImport } from './routes/api/session/$id'
import { Route as ApiRelationshipIdRouteImport } from './routes/api/relationship/$id'
import { Route as ApiPublicWorkflowsRouteImport } from './routes/api/public/workflows'
import { Route as ApiInvestigationIdRouteImport } from './routes/api/investigation/$id'
import { Route as ApiEvidenceIdRouteImport } from './routes/api/evidence/$id'
import { Route as ApiEntityIdRouteImport } from './routes/api/entity/$id'
import { Route as ApiCopilotTranscribeRouteImport } from './routes/api/copilot/transcribe'
import { Route as ApiCopilotQueryRouteImport } from './routes/api/copilot/query'
import { Route as ApiPublicHooksMibcTickRouteImport } from './routes/api/public/hooks/mibc-tick'
import { Route as ApiPublicDevSeedRoleRouteImport } from './routes/api/public/dev/seed-role'

const VesselRoute = VesselRouteImport.update({
  id: '/vessel',
  path: '/vessel',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueLeakageRoute = RevenueLeakageRouteImport.update({
  id: '/revenue-leakage',
  path: '/revenue-leakage',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsRoute = PortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnershipRoute = OwnershipRouteImport.update({
  id: '/ownership',
  path: '/ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationalKnowledgeRoute = OperationalKnowledgeRouteImport.update({
  id: '/operational-knowledge',
  path: '/operational-knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const NationalRiskRoute = NationalRiskRouteImport.update({
  id: '/national-risk',
  path: '/national-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestRoute = ManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeGraphRoute = KnowledgeGraphRouteImport.update({
  id: '/knowledge-graph',
  path: '/knowledge-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsWorkflowRoute = InvestigationsWorkflowRouteImport.update({
  id: '/investigations-workflow',
  path: '/investigations-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigateRoute = InvestigateRouteImport.update({
  id: '/investigate',
  path: '/investigate',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceEvidenceRoute = IntelligenceEvidenceRouteImport.update({
  id: '/intelligence-evidence',
  path: '/intelligence-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectRoute = DetectRouteImport.update({
  id: '/detect',
  path: '/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideRoute = DecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoWorkspaceRoute = CargoWorkspaceRouteImport.update({
  id: '/cargo-workspace',
  path: '/cargo-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingCentreRoute = BriefingCentreRouteImport.update({
  id: '/briefing-centre',
  path: '/briefing-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/workspace/',
  path: '/workspace/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIndexRoute = ShareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShareRoute,
} as any)
const InvestigateIndexRoute = InvestigateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvestigateRoute,
} as any)
const DecideIndexRoute = DecideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DecideRoute,
} as any)
const CargoWorkspaceIndexRoute = CargoWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CargoWorkspaceRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/workspace/$id',
  path: '/workspace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareQueueRoute = ShareQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => ShareRoute,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShareRoute,
} as any)
const InvestigateOpenRoute = InvestigateOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => InvestigateRoute,
} as any)
const InvestigateIdRoute = InvestigateIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvestigateRoute,
} as any)
const EntityIdRoute = EntityIdRouteImport.update({
  id: '/entity/$id',
  path: '/entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideQueueRoute = DecideQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DecideRoute,
} as any)
const DecideIdRoute = DecideIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DecideRoute,
} as any)
const CargoWorkspaceCentreRoute = CargoWorkspaceCentreRouteImport.update({
  id: '/$centre',
  path: '/$centre',
  getParentRoute: () => CargoWorkspaceRoute,
} as any)
const AdminProviderHealthRoute = AdminProviderHealthRouteImport.update({
  id: '/admin/provider-health',
  path: '/admin/provider-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectionContractRoute = AdminProjectionContractRouteImport.update({
  id: '/admin/projection-contract',
  path: '/admin/projection-contract',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOsintRoute = AdminOsintRouteImport.update({
  id: '/admin/osint',
  path: '/admin/osint',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConnectorsRoute = AdminConnectorsRouteImport.update({
  id: '/admin/connectors',
  path: '/admin/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionIdRoute = ApiSessionIdRouteImport.update({
  id: '/api/session/$id',
  path: '/api/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRelationshipIdRoute = ApiRelationshipIdRouteImport.update({
  id: '/api/relationship/$id',
  path: '/api/relationship/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkflowsRoute = ApiPublicWorkflowsRouteImport.update({
  id: '/api/public/workflows',
  path: '/api/public/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvestigationIdRoute = ApiInvestigationIdRouteImport.update({
  id: '/api/investigation/$id',
  path: '/api/investigation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenceIdRoute = ApiEvidenceIdRouteImport.update({
  id: '/api/evidence/$id',
  path: '/api/evidence/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEntityIdRoute = ApiEntityIdRouteImport.update({
  id: '/api/entity/$id',
  path: '/api/entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotTranscribeRoute = ApiCopilotTranscribeRouteImport.update({
  id: '/api/copilot/transcribe',
  path: '/api/copilot/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotQueryRoute = ApiCopilotQueryRouteImport.update({
  id: '/api/copilot/query',
  path: '/api/copilot/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMibcTickRoute = ApiPublicHooksMibcTickRouteImport.update({
  id: '/api/public/hooks/mibc-tick',
  path: '/api/public/hooks/mibc-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDevSeedRoleRoute = ApiPublicDevSeedRoleRouteImport.update({
  id: '/api/public/dev/seed-role',
  path: '/api/public/dev/seed-role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/briefing-centre': typeof BriefingCentreRoute
  '/cargo': typeof CargoRoute
  '/cargo-workspace': typeof CargoWorkspaceRouteWithChildren
  '/command-center': typeof CommandCenterRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/decide': typeof DecideRouteWithChildren
  '/detect': typeof DetectRoute
  '/evidence': typeof EvidenceRoute
  '/intelligence-evidence': typeof IntelligenceEvidenceRoute
  '/investigate': typeof InvestigateRouteWithChildren
  '/investigations': typeof InvestigationsRoute
  '/investigations-workflow': typeof InvestigationsWorkflowRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/manifest': typeof ManifestRoute
  '/memory': typeof MemoryRoute
  '/missions': typeof MissionsRoute
  '/national-risk': typeof NationalRiskRoute
  '/observability': typeof ObservabilityRoute
  '/operational-knowledge': typeof OperationalKnowledgeRoute
  '/ownership': typeof OwnershipRoute
  '/ports': typeof PortsRoute
  '/predictions': typeof PredictionsRoute
  '/revenue': typeof RevenueRoute
  '/revenue-leakage': typeof RevenueLeakageRoute
  '/share': typeof ShareRouteWithChildren
  '/vessel': typeof VesselRoute
  '/admin/connectors': typeof AdminConnectorsRoute
  '/admin/osint': typeof AdminOsintRoute
  '/admin/projection-contract': typeof AdminProjectionContractRoute
  '/admin/provider-health': typeof AdminProviderHealthRoute
  '/cargo-workspace/$centre': typeof CargoWorkspaceCentreRoute
  '/decide/$id': typeof DecideIdRoute
  '/decide/queue': typeof DecideQueueRoute
  '/entity/$id': typeof EntityIdRoute
  '/investigate/$id': typeof InvestigateIdRoute
  '/investigate/open': typeof InvestigateOpenRoute
  '/share/$id': typeof ShareIdRoute
  '/share/queue': typeof ShareQueueRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cargo-workspace/': typeof CargoWorkspaceIndexRoute
  '/decide/': typeof DecideIndexRoute
  '/investigate/': typeof InvestigateIndexRoute
  '/share/': typeof ShareIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/api/copilot/query': typeof ApiCopilotQueryRoute
  '/api/copilot/transcribe': typeof ApiCopilotTranscribeRoute
  '/api/entity/$id': typeof ApiEntityIdRoute
  '/api/evidence/$id': typeof ApiEvidenceIdRoute
  '/api/investigation/$id': typeof ApiInvestigationIdRoute
  '/api/public/workflows': typeof ApiPublicWorkflowsRoute
  '/api/relationship/$id': typeof ApiRelationshipIdRoute
  '/api/session/$id': typeof ApiSessionIdRoute
  '/api/public/dev/seed-role': typeof ApiPublicDevSeedRoleRoute
  '/api/public/hooks/mibc-tick': typeof ApiPublicHooksMibcTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/briefing-centre': typeof BriefingCentreRoute
  '/cargo': typeof CargoRoute
  '/command-center': typeof CommandCenterRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/detect': typeof DetectRoute
  '/evidence': typeof EvidenceRoute
  '/intelligence-evidence': typeof IntelligenceEvidenceRoute
  '/investigations': typeof InvestigationsRoute
  '/investigations-workflow': typeof InvestigationsWorkflowRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/manifest': typeof ManifestRoute
  '/memory': typeof MemoryRoute
  '/missions': typeof MissionsRoute
  '/national-risk': typeof NationalRiskRoute
  '/observability': typeof ObservabilityRoute
  '/operational-knowledge': typeof OperationalKnowledgeRoute
  '/ownership': typeof OwnershipRoute
  '/ports': typeof PortsRoute
  '/predictions': typeof PredictionsRoute
  '/revenue': typeof RevenueRoute
  '/revenue-leakage': typeof RevenueLeakageRoute
  '/vessel': typeof VesselRoute
  '/admin/connectors': typeof AdminConnectorsRoute
  '/admin/osint': typeof AdminOsintRoute
  '/admin/projection-contract': typeof AdminProjectionContractRoute
  '/admin/provider-health': typeof AdminProviderHealthRoute
  '/cargo-workspace/$centre': typeof CargoWorkspaceCentreRoute
  '/decide/$id': typeof DecideIdRoute
  '/decide/queue': typeof DecideQueueRoute
  '/entity/$id': typeof EntityIdRoute
  '/investigate/$id': typeof InvestigateIdRoute
  '/investigate/open': typeof InvestigateOpenRoute
  '/share/$id': typeof ShareIdRoute
  '/share/queue': typeof ShareQueueRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/admin': typeof AdminIndexRoute
  '/cargo-workspace': typeof CargoWorkspaceIndexRoute
  '/decide': typeof DecideIndexRoute
  '/investigate': typeof InvestigateIndexRoute
  '/share': typeof ShareIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/api/copilot/query': typeof ApiCopilotQueryRoute
  '/api/copilot/transcribe': typeof ApiCopilotTranscribeRoute
  '/api/entity/$id': typeof ApiEntityIdRoute
  '/api/evidence/$id': typeof ApiEvidenceIdRoute
  '/api/investigation/$id': typeof ApiInvestigationIdRoute
  '/api/public/workflows': typeof ApiPublicWorkflowsRoute
  '/api/relationship/$id': typeof ApiRelationshipIdRoute
  '/api/session/$id': typeof ApiSessionIdRoute
  '/api/public/dev/seed-role': typeof ApiPublicDevSeedRoleRoute
  '/api/public/hooks/mibc-tick': typeof ApiPublicHooksMibcTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/briefing-centre': typeof BriefingCentreRoute
  '/cargo': typeof CargoRoute
  '/cargo-workspace': typeof CargoWorkspaceRouteWithChildren
  '/command-center': typeof CommandCenterRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/decide': typeof DecideRouteWithChildren
  '/detect': typeof DetectRoute
  '/evidence': typeof EvidenceRoute
  '/intelligence-evidence': typeof IntelligenceEvidenceRoute
  '/investigate': typeof InvestigateRouteWithChildren
  '/investigations': typeof InvestigationsRoute
  '/investigations-workflow': typeof InvestigationsWorkflowRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/manifest': typeof ManifestRoute
  '/memory': typeof MemoryRoute
  '/missions': typeof MissionsRoute
  '/national-risk': typeof NationalRiskRoute
  '/observability': typeof ObservabilityRoute
  '/operational-knowledge': typeof OperationalKnowledgeRoute
  '/ownership': typeof OwnershipRoute
  '/ports': typeof PortsRoute
  '/predictions': typeof PredictionsRoute
  '/revenue': typeof RevenueRoute
  '/revenue-leakage': typeof RevenueLeakageRoute
  '/share': typeof ShareRouteWithChildren
  '/vessel': typeof VesselRoute
  '/admin/connectors': typeof AdminConnectorsRoute
  '/admin/osint': typeof AdminOsintRoute
  '/admin/projection-contract': typeof AdminProjectionContractRoute
  '/admin/provider-health': typeof AdminProviderHealthRoute
  '/cargo-workspace/$centre': typeof CargoWorkspaceCentreRoute
  '/decide/$id': typeof DecideIdRoute
  '/decide/queue': typeof DecideQueueRoute
  '/entity/$id': typeof EntityIdRoute
  '/investigate/$id': typeof InvestigateIdRoute
  '/investigate/open': typeof InvestigateOpenRoute
  '/share/$id': typeof ShareIdRoute
  '/share/queue': typeof ShareQueueRoute
  '/workspace/$id': typeof WorkspaceIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cargo-workspace/': typeof CargoWorkspaceIndexRoute
  '/decide/': typeof DecideIndexRoute
  '/investigate/': typeof InvestigateIndexRoute
  '/share/': typeof ShareIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/api/copilot/query': typeof ApiCopilotQueryRoute
  '/api/copilot/transcribe': typeof ApiCopilotTranscribeRoute
  '/api/entity/$id': typeof ApiEntityIdRoute
  '/api/evidence/$id': typeof ApiEvidenceIdRoute
  '/api/investigation/$id': typeof ApiInvestigationIdRoute
  '/api/public/workflows': typeof ApiPublicWorkflowsRoute
  '/api/relationship/$id': typeof ApiRelationshipIdRoute
  '/api/session/$id': typeof ApiSessionIdRoute
  '/api/public/dev/seed-role': typeof ApiPublicDevSeedRoleRoute
  '/api/public/hooks/mibc-tick': typeof ApiPublicHooksMibcTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/auth'
    | '/briefing-centre'
    | '/cargo'
    | '/cargo-workspace'
    | '/command-center'
    | '/compliance'
    | '/copilot'
    | '/decide'
    | '/detect'
    | '/evidence'
    | '/intelligence-evidence'
    | '/investigate'
    | '/investigations'
    | '/investigations-workflow'
    | '/knowledge-graph'
    | '/manifest'
    | '/memory'
    | '/missions'
    | '/national-risk'
    | '/observability'
    | '/operational-knowledge'
    | '/ownership'
    | '/ports'
    | '/predictions'
    | '/revenue'
    | '/revenue-leakage'
    | '/share'
    | '/vessel'
    | '/admin/connectors'
    | '/admin/osint'
    | '/admin/projection-contract'
    | '/admin/provider-health'
    | '/cargo-workspace/$centre'
    | '/decide/$id'
    | '/decide/queue'
    | '/entity/$id'
    | '/investigate/$id'
    | '/investigate/open'
    | '/share/$id'
    | '/share/queue'
    | '/workspace/$id'
    | '/admin/'
    | '/cargo-workspace/'
    | '/decide/'
    | '/investigate/'
    | '/share/'
    | '/workspace/'
    | '/api/copilot/query'
    | '/api/copilot/transcribe'
    | '/api/entity/$id'
    | '/api/evidence/$id'
    | '/api/investigation/$id'
    | '/api/public/workflows'
    | '/api/relationship/$id'
    | '/api/session/$id'
    | '/api/public/dev/seed-role'
    | '/api/public/hooks/mibc-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/auth'
    | '/briefing-centre'
    | '/cargo'
    | '/command-center'
    | '/compliance'
    | '/copilot'
    | '/detect'
    | '/evidence'
    | '/intelligence-evidence'
    | '/investigations'
    | '/investigations-workflow'
    | '/knowledge-graph'
    | '/manifest'
    | '/memory'
    | '/missions'
    | '/national-risk'
    | '/observability'
    | '/operational-knowledge'
    | '/ownership'
    | '/ports'
    | '/predictions'
    | '/revenue'
    | '/revenue-leakage'
    | '/vessel'
    | '/admin/connectors'
    | '/admin/osint'
    | '/admin/projection-contract'
    | '/admin/provider-health'
    | '/cargo-workspace/$centre'
    | '/decide/$id'
    | '/decide/queue'
    | '/entity/$id'
    | '/investigate/$id'
    | '/investigate/open'
    | '/share/$id'
    | '/share/queue'
    | '/workspace/$id'
    | '/admin'
    | '/cargo-workspace'
    | '/decide'
    | '/investigate'
    | '/share'
    | '/workspace'
    | '/api/copilot/query'
    | '/api/copilot/transcribe'
    | '/api/entity/$id'
    | '/api/evidence/$id'
    | '/api/investigation/$id'
    | '/api/public/workflows'
    | '/api/relationship/$id'
    | '/api/session/$id'
    | '/api/public/dev/seed-role'
    | '/api/public/hooks/mibc-tick'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/auth'
    | '/briefing-centre'
    | '/cargo'
    | '/cargo-workspace'
    | '/command-center'
    | '/compliance'
    | '/copilot'
    | '/decide'
    | '/detect'
    | '/evidence'
    | '/intelligence-evidence'
    | '/investigate'
    | '/investigations'
    | '/investigations-workflow'
    | '/knowledge-graph'
    | '/manifest'
    | '/memory'
    | '/missions'
    | '/national-risk'
    | '/observability'
    | '/operational-knowledge'
    | '/ownership'
    | '/ports'
    | '/predictions'
    | '/revenue'
    | '/revenue-leakage'
    | '/share'
    | '/vessel'
    | '/admin/connectors'
    | '/admin/osint'
    | '/admin/projection-contract'
    | '/admin/provider-health'
    | '/cargo-workspace/$centre'
    | '/decide/$id'
    | '/decide/queue'
    | '/entity/$id'
    | '/investigate/$id'
    | '/investigate/open'
    | '/share/$id'
    | '/share/queue'
    | '/workspace/$id'
    | '/admin/'
    | '/cargo-workspace/'
    | '/decide/'
    | '/investigate/'
    | '/share/'
    | '/workspace/'
    | '/api/copilot/query'
    | '/api/copilot/transcribe'
    | '/api/entity/$id'
    | '/api/evidence/$id'
    | '/api/investigation/$id'
    | '/api/public/workflows'
    | '/api/relationship/$id'
    | '/api/session/$id'
    | '/api/public/dev/seed-role'
    | '/api/public/hooks/mibc-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  BriefingCentreRoute: typeof BriefingCentreRoute
  CargoRoute: typeof CargoRoute
  CargoWorkspaceRoute: typeof CargoWorkspaceRouteWithChildren
  CommandCenterRoute: typeof CommandCenterRoute
  ComplianceRoute: typeof ComplianceRoute
  CopilotRoute: typeof CopilotRoute
  DecideRoute: typeof DecideRouteWithChildren
  DetectRoute: typeof DetectRoute
  EvidenceRoute: typeof EvidenceRoute
  IntelligenceEvidenceRoute: typeof IntelligenceEvidenceRoute
  InvestigateRoute: typeof InvestigateRouteWithChildren
  InvestigationsRoute: typeof InvestigationsRoute
  InvestigationsWorkflowRoute: typeof InvestigationsWorkflowRoute
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  ManifestRoute: typeof ManifestRoute
  MemoryRoute: typeof MemoryRoute
  MissionsRoute: typeof MissionsRoute
  NationalRiskRoute: typeof NationalRiskRoute
  ObservabilityRoute: typeof ObservabilityRoute
  OperationalKnowledgeRoute: typeof OperationalKnowledgeRoute
  OwnershipRoute: typeof OwnershipRoute
  PortsRoute: typeof PortsRoute
  PredictionsRoute: typeof PredictionsRoute
  RevenueRoute: typeof RevenueRoute
  RevenueLeakageRoute: typeof RevenueLeakageRoute
  ShareRoute: typeof ShareRouteWithChildren
  VesselRoute: typeof VesselRoute
  AdminConnectorsRoute: typeof AdminConnectorsRoute
  AdminOsintRoute: typeof AdminOsintRoute
  AdminProjectionContractRoute: typeof AdminProjectionContractRoute
  AdminProviderHealthRoute: typeof AdminProviderHealthRoute
  EntityIdRoute: typeof EntityIdRoute
  WorkspaceIdRoute: typeof WorkspaceIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  ApiCopilotQueryRoute: typeof ApiCopilotQueryRoute
  ApiCopilotTranscribeRoute: typeof ApiCopilotTranscribeRoute
  ApiEntityIdRoute: typeof ApiEntityIdRoute
  ApiEvidenceIdRoute: typeof ApiEvidenceIdRoute
  ApiInvestigationIdRoute: typeof ApiInvestigationIdRoute
  ApiPublicWorkflowsRoute: typeof ApiPublicWorkflowsRoute
  ApiRelationshipIdRoute: typeof ApiRelationshipIdRoute
  ApiSessionIdRoute: typeof ApiSessionIdRoute
  ApiPublicDevSeedRoleRoute: typeof ApiPublicDevSeedRoleRoute
  ApiPublicHooksMibcTickRoute: typeof ApiPublicHooksMibcTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vessel': {
      id: '/vessel'
      path: '/vessel'
      fullPath: '/vessel'
      preLoaderRoute: typeof VesselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue-leakage': {
      id: '/revenue-leakage'
      path: '/revenue-leakage'
      fullPath: '/revenue-leakage'
      preLoaderRoute: typeof RevenueLeakageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports': {
      id: '/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof PortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ownership': {
      id: '/ownership'
      path: '/ownership'
      fullPath: '/ownership'
      preLoaderRoute: typeof OwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operational-knowledge': {
      id: '/operational-knowledge'
      path: '/operational-knowledge'
      fullPath: '/operational-knowledge'
      preLoaderRoute: typeof OperationalKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/national-risk': {
      id: '/national-risk'
      path: '/national-risk'
      fullPath: '/national-risk'
      preLoaderRoute: typeof NationalRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest': {
      id: '/manifest'
      path: '/manifest'
      fullPath: '/manifest'
      preLoaderRoute: typeof ManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-graph': {
      id: '/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof KnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations-workflow': {
      id: '/investigations-workflow'
      path: '/investigations-workflow'
      fullPath: '/investigations-workflow'
      preLoaderRoute: typeof InvestigationsWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate': {
      id: '/investigate'
      path: '/investigate'
      fullPath: '/investigate'
      preLoaderRoute: typeof InvestigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence-evidence': {
      id: '/intelligence-evidence'
      path: '/intelligence-evidence'
      fullPath: '/intelligence-evidence'
      preLoaderRoute: typeof IntelligenceEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detect': {
      id: '/detect'
      path: '/detect'
      fullPath: '/detect'
      preLoaderRoute: typeof DetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide': {
      id: '/decide'
      path: '/decide'
      fullPath: '/decide'
      preLoaderRoute: typeof DecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo-workspace': {
      id: '/cargo-workspace'
      path: '/cargo-workspace'
      fullPath: '/cargo-workspace'
      preLoaderRoute: typeof CargoWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing-centre': {
      id: '/briefing-centre'
      path: '/briefing-centre'
      fullPath: '/briefing-centre'
      preLoaderRoute: typeof BriefingCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/': {
      id: '/share/'
      path: '/'
      fullPath: '/share/'
      preLoaderRoute: typeof ShareIndexRouteImport
      parentRoute: typeof ShareRoute
    }
    '/investigate/': {
      id: '/investigate/'
      path: '/'
      fullPath: '/investigate/'
      preLoaderRoute: typeof InvestigateIndexRouteImport
      parentRoute: typeof InvestigateRoute
    }
    '/decide/': {
      id: '/decide/'
      path: '/'
      fullPath: '/decide/'
      preLoaderRoute: typeof DecideIndexRouteImport
      parentRoute: typeof DecideRoute
    }
    '/cargo-workspace/': {
      id: '/cargo-workspace/'
      path: '/'
      fullPath: '/cargo-workspace/'
      preLoaderRoute: typeof CargoWorkspaceIndexRouteImport
      parentRoute: typeof CargoWorkspaceRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$id': {
      id: '/workspace/$id'
      path: '/workspace/$id'
      fullPath: '/workspace/$id'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/queue': {
      id: '/share/queue'
      path: '/queue'
      fullPath: '/share/queue'
      preLoaderRoute: typeof ShareQueueRouteImport
      parentRoute: typeof ShareRoute
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof ShareRoute
    }
    '/investigate/open': {
      id: '/investigate/open'
      path: '/open'
      fullPath: '/investigate/open'
      preLoaderRoute: typeof InvestigateOpenRouteImport
      parentRoute: typeof InvestigateRoute
    }
    '/investigate/$id': {
      id: '/investigate/$id'
      path: '/$id'
      fullPath: '/investigate/$id'
      preLoaderRoute: typeof InvestigateIdRouteImport
      parentRoute: typeof InvestigateRoute
    }
    '/entity/$id': {
      id: '/entity/$id'
      path: '/entity/$id'
      fullPath: '/entity/$id'
      preLoaderRoute: typeof EntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide/queue': {
      id: '/decide/queue'
      path: '/queue'
      fullPath: '/decide/queue'
      preLoaderRoute: typeof DecideQueueRouteImport
      parentRoute: typeof DecideRoute
    }
    '/decide/$id': {
      id: '/decide/$id'
      path: '/$id'
      fullPath: '/decide/$id'
      preLoaderRoute: typeof DecideIdRouteImport
      parentRoute: typeof DecideRoute
    }
    '/cargo-workspace/$centre': {
      id: '/cargo-workspace/$centre'
      path: '/$centre'
      fullPath: '/cargo-workspace/$centre'
      preLoaderRoute: typeof CargoWorkspaceCentreRouteImport
      parentRoute: typeof CargoWorkspaceRoute
    }
    '/admin/provider-health': {
      id: '/admin/provider-health'
      path: '/admin/provider-health'
      fullPath: '/admin/provider-health'
      preLoaderRoute: typeof AdminProviderHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projection-contract': {
      id: '/admin/projection-contract'
      path: '/admin/projection-contract'
      fullPath: '/admin/projection-contract'
      preLoaderRoute: typeof AdminProjectionContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/osint': {
      id: '/admin/osint'
      path: '/admin/osint'
      fullPath: '/admin/osint'
      preLoaderRoute: typeof AdminOsintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/connectors': {
      id: '/admin/connectors'
      path: '/admin/connectors'
      fullPath: '/admin/connectors'
      preLoaderRoute: typeof AdminConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session/$id': {
      id: '/api/session/$id'
      path: '/api/session/$id'
      fullPath: '/api/session/$id'
      preLoaderRoute: typeof ApiSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/relationship/$id': {
      id: '/api/relationship/$id'
      path: '/api/relationship/$id'
      fullPath: '/api/relationship/$id'
      preLoaderRoute: typeof ApiRelationshipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workflows': {
      id: '/api/public/workflows'
      path: '/api/public/workflows'
      fullPath: '/api/public/workflows'
      preLoaderRoute: typeof ApiPublicWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/investigation/$id': {
      id: '/api/investigation/$id'
      path: '/api/investigation/$id'
      fullPath: '/api/investigation/$id'
      preLoaderRoute: typeof ApiInvestigationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidence/$id': {
      id: '/api/evidence/$id'
      path: '/api/evidence/$id'
      fullPath: '/api/evidence/$id'
      preLoaderRoute: typeof ApiEvidenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/entity/$id': {
      id: '/api/entity/$id'
      path: '/api/entity/$id'
      fullPath: '/api/entity/$id'
      preLoaderRoute: typeof ApiEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/transcribe': {
      id: '/api/copilot/transcribe'
      path: '/api/copilot/transcribe'
      fullPath: '/api/copilot/transcribe'
      preLoaderRoute: typeof ApiCopilotTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/query': {
      id: '/api/copilot/query'
      path: '/api/copilot/query'
      fullPath: '/api/copilot/query'
      preLoaderRoute: typeof ApiCopilotQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mibc-tick': {
      id: '/api/public/hooks/mibc-tick'
      path: '/api/public/hooks/mibc-tick'
      fullPath: '/api/public/hooks/mibc-tick'
      preLoaderRoute: typeof ApiPublicHooksMibcTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dev/seed-role': {
      id: '/api/public/dev/seed-role'
      path: '/api/public/dev/seed-role'
      fullPath: '/api/public/dev/seed-role'
      preLoaderRoute: typeof ApiPublicDevSeedRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CargoWorkspaceRouteChildren {
  CargoWorkspaceCentreRoute: typeof CargoWorkspaceCentreRoute
  CargoWorkspaceIndexRoute: typeof CargoWorkspaceIndexRoute
}

const CargoWorkspaceRouteChildren: CargoWorkspaceRouteChildren = {
  CargoWorkspaceCentreRoute: CargoWorkspaceCentreRoute,
  CargoWorkspaceIndexRoute: CargoWorkspaceIndexRoute,
}

const CargoWorkspaceRouteWithChildren = CargoWorkspaceRoute._addFileChildren(
  CargoWorkspaceRouteChildren,
)

interface DecideRouteChildren {
  DecideIdRoute: typeof DecideIdRoute
  DecideQueueRoute: typeof DecideQueueRoute
  DecideIndexRoute: typeof DecideIndexRoute
}

const DecideRouteChildren: DecideRouteChildren = {
  DecideIdRoute: DecideIdRoute,
  DecideQueueRoute: DecideQueueRoute,
  DecideIndexRoute: DecideIndexRoute,
}

const DecideRouteWithChildren =
  DecideRoute._addFileChildren(DecideRouteChildren)

interface InvestigateRouteChildren {
  InvestigateIdRoute: typeof InvestigateIdRoute
  InvestigateOpenRoute: typeof InvestigateOpenRoute
  InvestigateIndexRoute: typeof InvestigateIndexRoute
}

const InvestigateRouteChildren: InvestigateRouteChildren = {
  InvestigateIdRoute: InvestigateIdRoute,
  InvestigateOpenRoute: InvestigateOpenRoute,
  InvestigateIndexRoute: InvestigateIndexRoute,
}

const InvestigateRouteWithChildren = InvestigateRoute._addFileChildren(
  InvestigateRouteChildren,
)

interface ShareRouteChildren {
  ShareIdRoute: typeof ShareIdRoute
  ShareQueueRoute: typeof ShareQueueRoute
  ShareIndexRoute: typeof ShareIndexRoute
}

const ShareRouteChildren: ShareRouteChildren = {
  ShareIdRoute: ShareIdRoute,
  ShareQueueRoute: ShareQueueRoute,
  ShareIndexRoute: ShareIndexRoute,
}

const ShareRouteWithChildren = ShareRoute._addFileChildren(ShareRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  BriefingCentreRoute: BriefingCentreRoute,
  CargoRoute: CargoRoute,
  CargoWorkspaceRoute: CargoWorkspaceRouteWithChildren,
  CommandCenterRoute: CommandCenterRoute,
  ComplianceRoute: ComplianceRoute,
  CopilotRoute: CopilotRoute,
  DecideRoute: DecideRouteWithChildren,
  DetectRoute: DetectRoute,
  EvidenceRoute: EvidenceRoute,
  IntelligenceEvidenceRoute: IntelligenceEvidenceRoute,
  InvestigateRoute: InvestigateRouteWithChildren,
  InvestigationsRoute: InvestigationsRoute,
  InvestigationsWorkflowRoute: InvestigationsWorkflowRoute,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  ManifestRoute: ManifestRoute,
  MemoryRoute: MemoryRoute,
  MissionsRoute: MissionsRoute,
  NationalRiskRoute: NationalRiskRoute,
  ObservabilityRoute: ObservabilityRoute,
  OperationalKnowledgeRoute: OperationalKnowledgeRoute,
  OwnershipRoute: OwnershipRoute,
  PortsRoute: PortsRoute,
  PredictionsRoute: PredictionsRoute,
  RevenueRoute: RevenueRoute,
  RevenueLeakageRoute: RevenueLeakageRoute,
  ShareRoute: ShareRouteWithChildren,
  VesselRoute: VesselRoute,
  AdminConnectorsRoute: AdminConnectorsRoute,
  AdminOsintRoute: AdminOsintRoute,
  AdminProjectionContractRoute: AdminProjectionContractRoute,
  AdminProviderHealthRoute: AdminProviderHealthRoute,
  EntityIdRoute: EntityIdRoute,
  WorkspaceIdRoute: WorkspaceIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  ApiCopilotQueryRoute: ApiCopilotQueryRoute,
  ApiCopilotTranscribeRoute: ApiCopilotTranscribeRoute,
  ApiEntityIdRoute: ApiEntityIdRoute,
  ApiEvidenceIdRoute: ApiEvidenceIdRoute,
  ApiInvestigationIdRoute: ApiInvestigationIdRoute,
  ApiPublicWorkflowsRoute: ApiPublicWorkflowsRoute,
  ApiRelationshipIdRoute: ApiRelationshipIdRoute,
  ApiSessionIdRoute: ApiSessionIdRoute,
  ApiPublicDevSeedRoleRoute: ApiPublicDevSeedRoleRoute,
  ApiPublicHooksMibcTickRoute: ApiPublicHooksMibcTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
