/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VesselRouteImport } from './routes/vessel'
import { Route as ShareRouteImport } from './routes/share'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as PortsRouteImport } from './routes/ports'
import { Route as OwnershipRouteImport } from './routes/ownership'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ManifestRouteImport } from './routes/manifest'
import { Route as InvestigateRouteImport } from './routes/investigate'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as DetectRouteImport } from './routes/detect'
import { Route as DecideRouteImport } from './routes/decide'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareIndexRouteImport } from './routes/share.index'
import { Route as InvestigateIndexRouteImport } from './routes/investigate.index'
import { Route as DecideIndexRouteImport } from './routes/decide.index'
import { Route as ShareQueueRouteImport } from './routes/share.queue'
import { Route as ShareIdRouteImport } from './routes/share.$id'
import { Route as InvestigateOpenRouteImport } from './routes/investigate.open'
import { Route as InvestigateIdRouteImport } from './routes/investigate.$id'
import { Route as EntityIdRouteImport } from './routes/entity.$id'
import { Route as DecideQueueRouteImport } from './routes/decide.queue'
import { Route as DecideIdRouteImport } from './routes/decide.$id'
import { Route as ApiSessionIdRouteImport } from './routes/api/session/$id'
import { Route as ApiRelationshipIdRouteImport } from './routes/api/relationship/$id'
import { Route as ApiPublicWorkflowsRouteImport } from './routes/api/public/workflows'
import { Route as ApiInvestigationIdRouteImport } from './routes/api/investigation/$id'
import { Route as ApiEvidenceIdRouteImport } from './routes/api/evidence/$id'
import { Route as ApiEntityIdRouteImport } from './routes/api/entity/$id'
import { Route as ApiCopilotQueryRouteImport } from './routes/api/copilot/query'
import { Route as ApiPublicDevSeedRoleRouteImport } from './routes/api/public/dev/seed-role'

const VesselRoute = VesselRouteImport.update({
  id: '/vessel',
  path: '/vessel',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsRoute = PortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnershipRoute = OwnershipRouteImport.update({
  id: '/ownership',
  path: '/ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestRoute = ManifestRouteImport.update({
  id: '/manifest',
  path: '/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigateRoute = InvestigateRouteImport.update({
  id: '/investigate',
  path: '/investigate',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectRoute = DetectRouteImport.update({
  id: '/detect',
  path: '/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideRoute = DecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIndexRoute = ShareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShareRoute,
} as any)
const InvestigateIndexRoute = InvestigateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvestigateRoute,
} as any)
const DecideIndexRoute = DecideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DecideRoute,
} as any)
const ShareQueueRoute = ShareQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => ShareRoute,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShareRoute,
} as any)
const InvestigateOpenRoute = InvestigateOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => InvestigateRoute,
} as any)
const InvestigateIdRoute = InvestigateIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvestigateRoute,
} as any)
const EntityIdRoute = EntityIdRouteImport.update({
  id: '/entity/$id',
  path: '/entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideQueueRoute = DecideQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DecideRoute,
} as any)
const DecideIdRoute = DecideIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DecideRoute,
} as any)
const ApiSessionIdRoute = ApiSessionIdRouteImport.update({
  id: '/api/session/$id',
  path: '/api/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRelationshipIdRoute = ApiRelationshipIdRouteImport.update({
  id: '/api/relationship/$id',
  path: '/api/relationship/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkflowsRoute = ApiPublicWorkflowsRouteImport.update({
  id: '/api/public/workflows',
  path: '/api/public/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvestigationIdRoute = ApiInvestigationIdRouteImport.update({
  id: '/api/investigation/$id',
  path: '/api/investigation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenceIdRoute = ApiEvidenceIdRouteImport.update({
  id: '/api/evidence/$id',
  path: '/api/evidence/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEntityIdRoute = ApiEntityIdRouteImport.update({
  id: '/api/entity/$id',
  path: '/api/entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotQueryRoute = ApiCopilotQueryRouteImport.update({
  id: '/api/copilot/query',
  path: '/api/copilot/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDevSeedRoleRoute = ApiPublicDevSeedRoleRouteImport.update({
  id: '/api/public/dev/seed-role',
  path: '/api/public/dev/seed-role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/cargo': typeof CargoRoute
  '/command-center': typeof CommandCenterRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/decide': typeof DecideRouteWithChildren
  '/detect': typeof DetectRoute
  '/evidence': typeof EvidenceRoute
  '/investigate': typeof InvestigateRouteWithChildren
  '/manifest': typeof ManifestRoute
  '/memory': typeof MemoryRoute
  '/observability': typeof ObservabilityRoute
  '/ownership': typeof OwnershipRoute
  '/ports': typeof PortsRoute
  '/revenue': typeof RevenueRoute
  '/share': typeof ShareRouteWithChildren
  '/vessel': typeof VesselRoute
  '/decide/$id': typeof DecideIdRoute
  '/decide/queue': typeof DecideQueueRoute
  '/entity/$id': typeof EntityIdRoute
  '/investigate/$id': typeof InvestigateIdRoute
  '/investigate/open': typeof InvestigateOpenRoute
  '/share/$id': typeof ShareIdRoute
  '/share/queue': typeof ShareQueueRoute
  '/decide/': typeof DecideIndexRoute
  '/investigate/': typeof InvestigateIndexRoute
  '/share/': typeof ShareIndexRoute
  '/api/copilot/query': typeof ApiCopilotQueryRoute
  '/api/entity/$id': typeof ApiEntityIdRoute
  '/api/evidence/$id': typeof ApiEvidenceIdRoute
  '/api/investigation/$id': typeof ApiInvestigationIdRoute
  '/api/public/workflows': typeof ApiPublicWorkflowsRoute
  '/api/relationship/$id': typeof ApiRelationshipIdRoute
  '/api/session/$id': typeof ApiSessionIdRoute
  '/api/public/dev/seed-role': typeof ApiPublicDevSeedRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/cargo': typeof CargoRoute
  '/command-center': typeof CommandCenterRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/detect': typeof DetectRoute
  '/evidence': typeof EvidenceRoute
  '/manifest': typeof ManifestRoute
  '/memory': typeof MemoryRoute
  '/observability': typeof ObservabilityRoute
  '/ownership': typeof OwnershipRoute
  '/ports': typeof PortsRoute
  '/revenue': typeof RevenueRoute
  '/vessel': typeof VesselRoute
  '/decide/$id': typeof DecideIdRoute
  '/decide/queue': typeof DecideQueueRoute
  '/entity/$id': typeof EntityIdRoute
  '/investigate/$id': typeof InvestigateIdRoute
  '/investigate/open': typeof InvestigateOpenRoute
  '/share/$id': typeof ShareIdRoute
  '/share/queue': typeof ShareQueueRoute
  '/decide': typeof DecideIndexRoute
  '/investigate': typeof InvestigateIndexRoute
  '/share': typeof ShareIndexRoute
  '/api/copilot/query': typeof ApiCopilotQueryRoute
  '/api/entity/$id': typeof ApiEntityIdRoute
  '/api/evidence/$id': typeof ApiEvidenceIdRoute
  '/api/investigation/$id': typeof ApiInvestigationIdRoute
  '/api/public/workflows': typeof ApiPublicWorkflowsRoute
  '/api/relationship/$id': typeof ApiRelationshipIdRoute
  '/api/session/$id': typeof ApiSessionIdRoute
  '/api/public/dev/seed-role': typeof ApiPublicDevSeedRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/cargo': typeof CargoRoute
  '/command-center': typeof CommandCenterRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/decide': typeof DecideRouteWithChildren
  '/detect': typeof DetectRoute
  '/evidence': typeof EvidenceRoute
  '/investigate': typeof InvestigateRouteWithChildren
  '/manifest': typeof ManifestRoute
  '/memory': typeof MemoryRoute
  '/observability': typeof ObservabilityRoute
  '/ownership': typeof OwnershipRoute
  '/ports': typeof PortsRoute
  '/revenue': typeof RevenueRoute
  '/share': typeof ShareRouteWithChildren
  '/vessel': typeof VesselRoute
  '/decide/$id': typeof DecideIdRoute
  '/decide/queue': typeof DecideQueueRoute
  '/entity/$id': typeof EntityIdRoute
  '/investigate/$id': typeof InvestigateIdRoute
  '/investigate/open': typeof InvestigateOpenRoute
  '/share/$id': typeof ShareIdRoute
  '/share/queue': typeof ShareQueueRoute
  '/decide/': typeof DecideIndexRoute
  '/investigate/': typeof InvestigateIndexRoute
  '/share/': typeof ShareIndexRoute
  '/api/copilot/query': typeof ApiCopilotQueryRoute
  '/api/entity/$id': typeof ApiEntityIdRoute
  '/api/evidence/$id': typeof ApiEvidenceIdRoute
  '/api/investigation/$id': typeof ApiInvestigationIdRoute
  '/api/public/workflows': typeof ApiPublicWorkflowsRoute
  '/api/relationship/$id': typeof ApiRelationshipIdRoute
  '/api/session/$id': typeof ApiSessionIdRoute
  '/api/public/dev/seed-role': typeof ApiPublicDevSeedRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/cargo'
    | '/command-center'
    | '/compliance'
    | '/copilot'
    | '/decide'
    | '/detect'
    | '/evidence'
    | '/investigate'
    | '/manifest'
    | '/memory'
    | '/observability'
    | '/ownership'
    | '/ports'
    | '/revenue'
    | '/share'
    | '/vessel'
    | '/decide/$id'
    | '/decide/queue'
    | '/entity/$id'
    | '/investigate/$id'
    | '/investigate/open'
    | '/share/$id'
    | '/share/queue'
    | '/decide/'
    | '/investigate/'
    | '/share/'
    | '/api/copilot/query'
    | '/api/entity/$id'
    | '/api/evidence/$id'
    | '/api/investigation/$id'
    | '/api/public/workflows'
    | '/api/relationship/$id'
    | '/api/session/$id'
    | '/api/public/dev/seed-role'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/cargo'
    | '/command-center'
    | '/compliance'
    | '/copilot'
    | '/detect'
    | '/evidence'
    | '/manifest'
    | '/memory'
    | '/observability'
    | '/ownership'
    | '/ports'
    | '/revenue'
    | '/vessel'
    | '/decide/$id'
    | '/decide/queue'
    | '/entity/$id'
    | '/investigate/$id'
    | '/investigate/open'
    | '/share/$id'
    | '/share/queue'
    | '/decide'
    | '/investigate'
    | '/share'
    | '/api/copilot/query'
    | '/api/entity/$id'
    | '/api/evidence/$id'
    | '/api/investigation/$id'
    | '/api/public/workflows'
    | '/api/relationship/$id'
    | '/api/session/$id'
    | '/api/public/dev/seed-role'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/cargo'
    | '/command-center'
    | '/compliance'
    | '/copilot'
    | '/decide'
    | '/detect'
    | '/evidence'
    | '/investigate'
    | '/manifest'
    | '/memory'
    | '/observability'
    | '/ownership'
    | '/ports'
    | '/revenue'
    | '/share'
    | '/vessel'
    | '/decide/$id'
    | '/decide/queue'
    | '/entity/$id'
    | '/investigate/$id'
    | '/investigate/open'
    | '/share/$id'
    | '/share/queue'
    | '/decide/'
    | '/investigate/'
    | '/share/'
    | '/api/copilot/query'
    | '/api/entity/$id'
    | '/api/evidence/$id'
    | '/api/investigation/$id'
    | '/api/public/workflows'
    | '/api/relationship/$id'
    | '/api/session/$id'
    | '/api/public/dev/seed-role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  CargoRoute: typeof CargoRoute
  CommandCenterRoute: typeof CommandCenterRoute
  ComplianceRoute: typeof ComplianceRoute
  CopilotRoute: typeof CopilotRoute
  DecideRoute: typeof DecideRouteWithChildren
  DetectRoute: typeof DetectRoute
  EvidenceRoute: typeof EvidenceRoute
  InvestigateRoute: typeof InvestigateRouteWithChildren
  ManifestRoute: typeof ManifestRoute
  MemoryRoute: typeof MemoryRoute
  ObservabilityRoute: typeof ObservabilityRoute
  OwnershipRoute: typeof OwnershipRoute
  PortsRoute: typeof PortsRoute
  RevenueRoute: typeof RevenueRoute
  ShareRoute: typeof ShareRouteWithChildren
  VesselRoute: typeof VesselRoute
  EntityIdRoute: typeof EntityIdRoute
  ApiCopilotQueryRoute: typeof ApiCopilotQueryRoute
  ApiEntityIdRoute: typeof ApiEntityIdRoute
  ApiEvidenceIdRoute: typeof ApiEvidenceIdRoute
  ApiInvestigationIdRoute: typeof ApiInvestigationIdRoute
  ApiPublicWorkflowsRoute: typeof ApiPublicWorkflowsRoute
  ApiRelationshipIdRoute: typeof ApiRelationshipIdRoute
  ApiSessionIdRoute: typeof ApiSessionIdRoute
  ApiPublicDevSeedRoleRoute: typeof ApiPublicDevSeedRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vessel': {
      id: '/vessel'
      path: '/vessel'
      fullPath: '/vessel'
      preLoaderRoute: typeof VesselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports': {
      id: '/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof PortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ownership': {
      id: '/ownership'
      path: '/ownership'
      fullPath: '/ownership'
      preLoaderRoute: typeof OwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest': {
      id: '/manifest'
      path: '/manifest'
      fullPath: '/manifest'
      preLoaderRoute: typeof ManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate': {
      id: '/investigate'
      path: '/investigate'
      fullPath: '/investigate'
      preLoaderRoute: typeof InvestigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detect': {
      id: '/detect'
      path: '/detect'
      fullPath: '/detect'
      preLoaderRoute: typeof DetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide': {
      id: '/decide'
      path: '/decide'
      fullPath: '/decide'
      preLoaderRoute: typeof DecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/': {
      id: '/share/'
      path: '/'
      fullPath: '/share/'
      preLoaderRoute: typeof ShareIndexRouteImport
      parentRoute: typeof ShareRoute
    }
    '/investigate/': {
      id: '/investigate/'
      path: '/'
      fullPath: '/investigate/'
      preLoaderRoute: typeof InvestigateIndexRouteImport
      parentRoute: typeof InvestigateRoute
    }
    '/decide/': {
      id: '/decide/'
      path: '/'
      fullPath: '/decide/'
      preLoaderRoute: typeof DecideIndexRouteImport
      parentRoute: typeof DecideRoute
    }
    '/share/queue': {
      id: '/share/queue'
      path: '/queue'
      fullPath: '/share/queue'
      preLoaderRoute: typeof ShareQueueRouteImport
      parentRoute: typeof ShareRoute
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof ShareRoute
    }
    '/investigate/open': {
      id: '/investigate/open'
      path: '/open'
      fullPath: '/investigate/open'
      preLoaderRoute: typeof InvestigateOpenRouteImport
      parentRoute: typeof InvestigateRoute
    }
    '/investigate/$id': {
      id: '/investigate/$id'
      path: '/$id'
      fullPath: '/investigate/$id'
      preLoaderRoute: typeof InvestigateIdRouteImport
      parentRoute: typeof InvestigateRoute
    }
    '/entity/$id': {
      id: '/entity/$id'
      path: '/entity/$id'
      fullPath: '/entity/$id'
      preLoaderRoute: typeof EntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide/queue': {
      id: '/decide/queue'
      path: '/queue'
      fullPath: '/decide/queue'
      preLoaderRoute: typeof DecideQueueRouteImport
      parentRoute: typeof DecideRoute
    }
    '/decide/$id': {
      id: '/decide/$id'
      path: '/$id'
      fullPath: '/decide/$id'
      preLoaderRoute: typeof DecideIdRouteImport
      parentRoute: typeof DecideRoute
    }
    '/api/session/$id': {
      id: '/api/session/$id'
      path: '/api/session/$id'
      fullPath: '/api/session/$id'
      preLoaderRoute: typeof ApiSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/relationship/$id': {
      id: '/api/relationship/$id'
      path: '/api/relationship/$id'
      fullPath: '/api/relationship/$id'
      preLoaderRoute: typeof ApiRelationshipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workflows': {
      id: '/api/public/workflows'
      path: '/api/public/workflows'
      fullPath: '/api/public/workflows'
      preLoaderRoute: typeof ApiPublicWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/investigation/$id': {
      id: '/api/investigation/$id'
      path: '/api/investigation/$id'
      fullPath: '/api/investigation/$id'
      preLoaderRoute: typeof ApiInvestigationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidence/$id': {
      id: '/api/evidence/$id'
      path: '/api/evidence/$id'
      fullPath: '/api/evidence/$id'
      preLoaderRoute: typeof ApiEvidenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/entity/$id': {
      id: '/api/entity/$id'
      path: '/api/entity/$id'
      fullPath: '/api/entity/$id'
      preLoaderRoute: typeof ApiEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/query': {
      id: '/api/copilot/query'
      path: '/api/copilot/query'
      fullPath: '/api/copilot/query'
      preLoaderRoute: typeof ApiCopilotQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dev/seed-role': {
      id: '/api/public/dev/seed-role'
      path: '/api/public/dev/seed-role'
      fullPath: '/api/public/dev/seed-role'
      preLoaderRoute: typeof ApiPublicDevSeedRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DecideRouteChildren {
  DecideIdRoute: typeof DecideIdRoute
  DecideQueueRoute: typeof DecideQueueRoute
  DecideIndexRoute: typeof DecideIndexRoute
}

const DecideRouteChildren: DecideRouteChildren = {
  DecideIdRoute: DecideIdRoute,
  DecideQueueRoute: DecideQueueRoute,
  DecideIndexRoute: DecideIndexRoute,
}

const DecideRouteWithChildren =
  DecideRoute._addFileChildren(DecideRouteChildren)

interface InvestigateRouteChildren {
  InvestigateIdRoute: typeof InvestigateIdRoute
  InvestigateOpenRoute: typeof InvestigateOpenRoute
  InvestigateIndexRoute: typeof InvestigateIndexRoute
}

const InvestigateRouteChildren: InvestigateRouteChildren = {
  InvestigateIdRoute: InvestigateIdRoute,
  InvestigateOpenRoute: InvestigateOpenRoute,
  InvestigateIndexRoute: InvestigateIndexRoute,
}

const InvestigateRouteWithChildren = InvestigateRoute._addFileChildren(
  InvestigateRouteChildren,
)

interface ShareRouteChildren {
  ShareIdRoute: typeof ShareIdRoute
  ShareQueueRoute: typeof ShareQueueRoute
  ShareIndexRoute: typeof ShareIndexRoute
}

const ShareRouteChildren: ShareRouteChildren = {
  ShareIdRoute: ShareIdRoute,
  ShareQueueRoute: ShareQueueRoute,
  ShareIndexRoute: ShareIndexRoute,
}

const ShareRouteWithChildren = ShareRoute._addFileChildren(ShareRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  CargoRoute: CargoRoute,
  CommandCenterRoute: CommandCenterRoute,
  ComplianceRoute: ComplianceRoute,
  CopilotRoute: CopilotRoute,
  DecideRoute: DecideRouteWithChildren,
  DetectRoute: DetectRoute,
  EvidenceRoute: EvidenceRoute,
  InvestigateRoute: InvestigateRouteWithChildren,
  ManifestRoute: ManifestRoute,
  MemoryRoute: MemoryRoute,
  ObservabilityRoute: ObservabilityRoute,
  OwnershipRoute: OwnershipRoute,
  PortsRoute: PortsRoute,
  RevenueRoute: RevenueRoute,
  ShareRoute: ShareRouteWithChildren,
  VesselRoute: VesselRoute,
  EntityIdRoute: EntityIdRoute,
  ApiCopilotQueryRoute: ApiCopilotQueryRoute,
  ApiEntityIdRoute: ApiEntityIdRoute,
  ApiEvidenceIdRoute: ApiEvidenceIdRoute,
  ApiInvestigationIdRoute: ApiInvestigationIdRoute,
  ApiPublicWorkflowsRoute: ApiPublicWorkflowsRoute,
  ApiRelationshipIdRoute: ApiRelationshipIdRoute,
  ApiSessionIdRoute: ApiSessionIdRoute,
  ApiPublicDevSeedRoleRoute: ApiPublicDevSeedRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
