
-- Seed Detect Intelligence Feed with realistic maritime signals.
-- Metadata carries display fields the UI needs (title, detail, status, vessel refs, investigation id).
INSERT INTO public.signals (id, observed_at, domain, statement, entity_id, confidence, severity, evidence_ids, metadata) VALUES
 (gen_random_uuid(), now() - interval '12 min', 'Vessel Movement', 'AIS blackout observed on MV Ocean Pearl · 2h 14m gap in transit lane, off Bonny', NULL, 'OBSERVED', 'HIGH', ARRAY[]::uuid[], '{"title":"AIS blackout observed on MV Ocean Pearl","detail":"2h 14m gap in transit lane, off Bonny","status":"NEW","vessel":"MV Ocean Pearl","imo":"9432187","investigationId":"INV-2026-00431","type":"Gaps"}'::jsonb),
 (gen_random_uuid(), now() - interval '38 min', 'Cargo', 'Declared cargo weight 18% below scale reading on BOL #MSKU8842119', NULL, 'INFERRED', 'HIGH', ARRAY[]::uuid[], '{"title":"Declared cargo weight 18% below scale reading","detail":"BOL #MSKU8842119 · Steel products","status":"NEW","investigationId":"INV-2026-00420","type":"Discrepancies"}'::jsonb),
 (gen_random_uuid(), now() - interval '1 hour', 'Ownership', 'Beneficial owner change on Crimson Endeavour Ltd · 3 new shell links observed within 30 days', NULL, 'INFERRED', 'HIGH', ARRAY[]::uuid[], '{"title":"Beneficial owner change · Crimson Endeavour Ltd","detail":"3 new shell links observed within 30 days","status":"ACK","investigationId":"INV-2026-00429","type":"Changes"}'::jsonb),
 (gen_random_uuid(), now() - interval '1 hour 20 min', 'Compliance', 'Sanction watchlist match observed · Blue Horizon Shipping (2-hop link to OFAC SDN via director)', NULL, 'VERIFIED', 'HIGH', ARRAY[]::uuid[], '{"title":"Sanction watchlist match · Blue Horizon Shipping","detail":"2-hop link to OFAC SDN via director","status":"NEW","investigationId":"INV-2026-00425","type":"Matches","source_id":"OFAC","source_name":"OFAC SDN List"}'::jsonb),
 (gen_random_uuid(), now() - interval '1 hour 40 min', 'Manifest', 'HS code mismatch observed on BOL #APLU7712004 · rebar declared, coils observed', NULL, 'OBSERVED', 'MEDIUM', ARRAY[]::uuid[], '{"title":"HS code mismatch · declared vs. observed","detail":"BOL #APLU7712004 · rebar declared, coils observed","status":"NEW","investigationId":"INV-2026-00432","type":"Discrepancies"}'::jsonb),
 (gen_random_uuid(), now() - interval '3 hours', 'Revenue', 'Duty base 22% below peer basis observed for consignee Northgate Logistics (3-month rolling)', NULL, 'INFERRED', 'MEDIUM', ARRAY[]::uuid[], '{"title":"Revenue basis anomaly · duty base 22% below peers","detail":"Consignee Northgate Logistics · 3-month rolling","status":"NEW","type":"Anomalies"}'::jsonb),
 (gen_random_uuid(), now() - interval '4 hours', 'Port Operations', 'Apapa berth queue depth exceeds 30 · congestion index 88 (critical band)', NULL, 'OBSERVED', 'MEDIUM', ARRAY[]::uuid[], '{"title":"Apapa berth queue depth exceeds 30","detail":"Congestion index 88 · critical band","status":"ACK","type":"Anomalies"}'::jsonb),
 (gen_random_uuid(), now() - interval '6 hours', 'Manifest', 'Duplicate BOL number observed across two consignments · BOL #MSKU8842119 filed twice within 48h', NULL, 'VERIFIED', 'MEDIUM', ARRAY[]::uuid[], '{"title":"Duplicate BOL number across two consignments","detail":"BOL #MSKU8842119 filed twice within 48h","status":"ACK","type":"Duplicates","source_id":"NCS","source_name":"Nigeria Customs Service"}'::jsonb),
 (gen_random_uuid(), now() - interval '8 hours', 'Cargo', 'Container seal mismatch observed on arrival · MSKU 8842119', NULL, 'OBSERVED', 'LOW', ARRAY[]::uuid[], '{"title":"Container seal mismatch on arrival","detail":"MSKU 8842119 · original vs. presented","status":"ACK","type":"Discrepancies"}'::jsonb),
 (gen_random_uuid(), now() - interval '11 hours', 'Vessel Movement', 'First observation of MV Bonny Trader entering EEZ · IMO 9781200', NULL, 'OBSERVED', 'LOW', ARRAY[]::uuid[], '{"title":"New vessel entering EEZ · first observation","detail":"MV Bonny Trader · IMO 9781200","status":"ACK","vessel":"MV Bonny Trader","imo":"9781200","type":"Changes"}'::jsonb),
 (gen_random_uuid(), now() - interval '15 hours', 'Alerts', 'Repeated speed anomaly observed on MV Ocean Pearl within 24h window', NULL, 'OBSERVED', 'MEDIUM', ARRAY[]::uuid[], '{"title":"Repeated speed anomaly · MV Ocean Pearl","detail":"3 observations within 24h","status":"NEW","vessel":"MV Ocean Pearl","imo":"9432187","type":"Anomalies"}'::jsonb),
 (gen_random_uuid(), now() - interval '18 hours', 'Compliance', 'Flag-of-convenience switch observed on Blue Horizon within 90-day window', NULL, 'OBSERVED', 'MEDIUM', ARRAY[]::uuid[], '{"title":"Flag switch observed · Blue Horizon","detail":"Marshall Is. → Panama within 90 days","status":"NEW","type":"Changes"}'::jsonb),
 (gen_random_uuid(), now() - interval '20 hours', 'Ownership', 'Director appointment change observed at Northgate Logistics · registry filing', NULL, 'CORROBORATED', 'LOW', ARRAY[]::uuid[], '{"title":"Director change · Northgate Logistics","detail":"Registry filing corroborated","status":"ACK","type":"Changes"}'::jsonb),
 (gen_random_uuid(), now() - interval '22 hours', 'Revenue', 'Under-declaration pattern observed across 4 filings by same broker', NULL, 'INFERRED', 'HIGH', ARRAY[]::uuid[], '{"title":"Under-declaration pattern · single broker","detail":"4 filings, aggregate variance ₦180M","status":"NEW","type":"Anomalies"}'::jsonb);
